# Global Security testing configurations
target:
  web_url: "http://127.0.0.1:8080"
  api_url: "http://127.0.0.1:8000"
  openapi_spec: "http://127.0.0.1:8000/openapi.json"

scans:
  sast:
    semgrep_severity: "WARNING"
    trivy_severity: "HIGH,CRITICAL"
  dast:
    spider_depth: 3
    active_scan: true
  api:
    newman_env: "environment.json"

credentials:
  test_user: "astronaut@orbitx.com"
  # Read passwords from ENV keys
  test_pass_env: "ORBITX_PASSWORD"
