[pytest]
testpaths = automation/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --html=automation/reports/report.html --self-contained-html
markers =
    ui: UI and E2E test cases
    auth: Authentication and authorization test cases
