/**
 * GroqChatService.js
 *
 * Handles client-side chat logic for the OrbitX app, communicating
 * with the backend chat proxy endpoint.
 * Respects OFFLINE_MODE and provides high-fidelity local mock replies when offline.
 */

import { BASE_URL, OFFLINE_MODE } from './api/orbitxApi';

class GroqChatService {
  constructor() {
    this.conversationHistory = [];
    this.baseUrl = BASE_URL;
    this.forceOffline = false;
  }

  /**
   * Set forced offline mode status (e.g. from UI fallback activation)
   */
  setForceOffline(value) {
    this.forceOffline = !!value;
  }

  /**
   * Evaluates if we should use the local simulator
   */
  isOfflineMode() {
    return OFFLINE_MODE || this.forceOffline;
  }

  /**
   * Generates premium mock space responses for offline usage.
   */
  getMockResponse(userMessage) {
    const msg = (userMessage || '').toLowerCase();

    if (msg.includes('black hole')) {
      return {
        response: "Commander, a black hole is a region of spacetime where gravity is so strong that nothing—not even light—can escape. It is formed when a massive star collapses at the end of its life cycle.\n\nThe boundary of a black hole is called the event horizon. Once anything crosses this boundary, it cannot escape. In the center of a black hole lies a singularity, where matter is crushed to infinite density. Would you like to know more about how we detect them, Commander?",
        model: "offline-tutor-sim",
      };
    }

    if (msg.includes('earth') || msg.includes('world') || msg.includes('home')) {
      return {
        response: "Earth, our home world, is the third planet from the Sun and the only astronomical object known to harbor life, Commander.\n\nAbout 71% of Earth's surface is covered with liquid water oceans, and it has a robust nitrogen-oxygen atmosphere that protects us from solar radiation. Earth is also equipped with a powerful magnetosphere generated by its rotating liquid iron outer core. It has exactly one natural satellite, Luna (the Moon).",
        model: "offline-tutor-sim",
      };
    }

    if (msg.includes('iss') || msg.includes('space station')) {
      return {
        response: "The International Space Station (ISS) is a modular space station in low Earth orbit. It is a collaborative project between NASA, Roscosmos, JAXA, ESA, and CSA, Commander.\n\nIt travels at a speed of about 27,600 km/h (17,100 mph), orbiting the Earth every 90 minutes! It serves as a microgravity and space environment research laboratory where crew members conduct experiments in biology, physics, and astronomy.",
        model: "offline-tutor-sim",
      };
    }

    if (msg.includes('mars') || msg.includes('red planet')) {
      return {
        response: "Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System. It is often referred to as the 'Red Planet' because iron minerals in its soil oxidize (rust), giving it a reddish appearance.\n\nMars has a thin atmosphere, polar ice caps, and features like Olympus Mons (the largest volcano in the Solar System) and Valles Marineris (a canyon system larger than the Grand Canyon). It has two moons, Phobos and Deimos.",
        model: "offline-tutor-sim",
      };
    }

    if (msg.includes('neutron') || msg.includes('pulsar')) {
      return {
        response: "Commander, neutron stars are the extremely dense collapsed cores of massive supergiant stars. They are so dense that a single teaspoon of neutron star material would weigh about 6 billion tons on Earth!\n\nSome neutron stars rotate extremely fast and emit beams of electromagnetic radiation, appearing to pulse from our perspective. These are called pulsars. They are truly the extreme physics labs of the cosmos.",
        model: "offline-tutor-sim",
      };
    }

    if (msg.includes('fact')) {
      const facts = [
        "One day on Venus is longer than one year on Venus! Venus takes 243 Earth days to rotate once on its axis, but only 225 Earth days to orbit the Sun.",
        "Space is completely silent. Because there is no atmosphere in space, sound waves have no medium to travel through.",
        "The footprints left by Apollo astronauts on the Moon will probably stay there for at least 100 million years because there is no wind or water to erode them.",
        "The Sun is massive! It accounts for 99.86% of all the mass in the entire Solar System.",
        "There are more trees on Earth than stars in the Milky Way galaxy! There are about 3 trillion trees on Earth, compared to 100-400 billion stars in our galaxy.",
      ];
      const randomFact = facts[Math.floor(Math.random() * facts.length)];
      return {
        response: `Here is a cosmic fact for you, Commander: ${randomFact} Space is full of surprises!`,
        model: "offline-tutor-sim",
      };
    }

    // Default reply
    return {
      response: `Commander, I received your message: "${userMessage}".\n\nI am currently running in Offline Simulation Mode because the FastAPI backend server is unreachable. To get full AI capabilities, please start the backend server by running the launch scripts (LAUNCH_ORBITX.bat) and ensure your devices are connected to the same network.\n\nIn the meantime, feel free to ask me about black holes, the ISS, Mars, neutron stars, or ask for a space fact!`,
      model: "offline-tutor-sim",
    };
  }

  /**
   * Send a message to the backend and return the AI reply.
   *
   * @param {string} userMessage - User's query.
   * @returns {Promise<{response: string, model: string}>}
   */
  async sendMessage(userMessage) {
    const trimmed = (userMessage || '').trim();
    if (!trimmed) {
      throw new Error('Please type a space question before sending.');
    }

    // Check offline mode
    if (this.isOfflineMode()) {
      console.log('[GroqChatService] OFFLINE_MODE is active. Returning mock local reply.');
      await new Promise((resolve) => setTimeout(resolve, 800)); // Simulate realistic network delay
      
      const mockReply = this.getMockResponse(trimmed);
      
      this.conversationHistory.push({ role: 'user', content: trimmed });
      this.conversationHistory.push({ role: 'assistant', content: mockReply.response });
      
      return mockReply;
    }

    // Refresh base URL
    this.baseUrl = BASE_URL;
    const chatEndpoint = `${this.baseUrl}/chat`;

    console.log(`[GroqChatService] Outbound POST request to: ${chatEndpoint}`);
    
    // Add user turn locally
    this.conversationHistory.push({ role: 'user', content: trimmed });

    // Send context history (limit to last 10 messages)
    const historySlice = this.conversationHistory.slice(-10);

    const controller = typeof AbortController !== 'undefined' ? new AbortController() : null;
    const timeoutMs = 15000; // Balanced timeout
    const timeoutId = setTimeout(() => {
      if (controller) {
        console.warn(`[GroqChatService] Request to ${chatEndpoint} timed out after ${timeoutMs}ms.`);
        controller.abort();
      }
    }, timeoutMs);

    try {
      console.log(`[GroqChatService] Payload message: "${trimmed}", history turns: ${historySlice.length}`);
      
      const res = await fetch(chatEndpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
        body: JSON.stringify({
          message: trimmed,
          history: historySlice,
        }),
        ...(controller ? { signal: controller.signal } : {}),
      });

      clearTimeout(timeoutId);

      console.log(`[GroqChatService] Inbound response status: ${res.status}`);

      if (!res.ok) {
        let errorMsg = `Server error (${res.status})`;
        try {
          const errData = await res.json();
          if (errData && errData.detail) {
            errorMsg = errData.detail;
          }
        } catch (_) {
          // Fallback if not JSON
        }
        console.warn(`[GroqChatService] Backend rejected payload. Message: ${errorMsg}`);
        throw new Error(errorMsg);
      }

      const data = await res.json();
      console.log(`[GroqChatService] Response successfully parsed. Model: ${data.model}`);

      // Add assistant turn locally
      this.conversationHistory.push({
        role: 'assistant',
        content: data.response,
      });

      return {
        response: data.response,
        model: data.model || 'groq',
      };
    } catch (error) {
      clearTimeout(timeoutId);

      // Remove the last user input from history since it failed to transmit successfully
      this.conversationHistory.pop();

      console.warn(`[GroqChatService] Network or API failure:`, error);

      if (error.name === 'AbortError') {
        throw new Error(
          'Connection timed out. The server took too long to respond. Please try again.'
        );
      }

      if (
        error.message.includes('Network request failed') ||
        error.message.includes('Failed to fetch')
      ) {
        throw new Error(
          `Cannot reach the OrbitX server at ${this.baseUrl}. Please verify that the FastAPI backend is running and that your phone is connected to the same Wi-Fi network.`
        );
      }

      throw error;
    }
  }

  /**
   * Reset local history
   */
  clearHistory() {
    this.conversationHistory = [];
  }
}

export default new GroqChatService();
