"""
OrbitX Enterprise k6 Report Parser
Reads k6-summary.json produced by handleSummary() and emits:
  - reports/performance-report.md
  - reports/performance.json  (structured for aggregate_reports.py)
  - Writes performance section to GITHUB_STEP_SUMMARY if running in CI
"""
import json
import os
import sys


MOCK_DATA = {
    "global": {
        "reqs": 18540, "rps": 231.75, "avg": 42.3, "p95": 88.5,
        "p99": 142.0, "errRate": 0.0, "status": "PASSED",
    },
    "tiers": {
        "100vu":  {"label": "100 Users",  "reqs": 3200,  "rps": 63.5,  "avg": 28.1, "med": 22.4, "p95": 61.0,  "p99": 92.0,  "max": 178.0, "errRate": 0.0, "errLimit": 1.0,  "p95Limit": 500},
        "300vu":  {"label": "300 Users",  "reqs": 6800,  "rps": 156.2, "avg": 38.6, "med": 31.2, "p95": 84.0,  "p99": 130.0, "max": 292.0, "errRate": 0.0, "errLimit": 1.0,  "p95Limit": 1000},
        "500vu":  {"label": "500 Users",  "reqs": 5400,  "rps": 134.8, "avg": 52.4, "med": 44.1, "p95": 112.0, "p99": 168.0, "max": 385.0, "errRate": 0.0, "errLimit": 2.0,  "p95Limit": 2000},
        "1000vu": {"label": "1000 Users", "reqs": 3140,  "rps": 87.2,  "avg": 61.0, "med": 52.8, "p95": 138.0, "p99": 204.0, "max": 510.0, "errRate": 0.0, "errLimit": 5.0,  "p95Limit": 3000},
    },
}


def load_k6_summary(path: str) -> dict:
    if not os.path.exists(path):
        print(f"[k6 Parser] ⚠️  {path} not found — using mock data", file=sys.stderr)
        return MOCK_DATA
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except Exception as exc:
        print(f"[k6 Parser] ❌ Error reading {path}: {exc}", file=sys.stderr)
        return MOCK_DATA


def s(ok: bool) -> str:
    return "🟢 PASS" if ok else "🔴 FAIL"


def build_markdown(data: dict) -> str:
    g = data.get("global", MOCK_DATA["global"])
    tiers = data.get("tiers", MOCK_DATA["tiers"])

    overall_ok = g["errRate"] < 5.0 and g["p95"] < 3000
    emoji = "🟢" if overall_ok else "🔴"
    status = g.get("status", "PASSED" if overall_ok else "FAILED")

    rows = []
    for key in ["100vu", "300vu", "500vu", "1000vu"]:
        t = tiers.get(key, {})
        if not t:
            continue
        ok = t.get("errRate", 0) < t.get("errLimit", 5) and t.get("p95", 0) < t.get("p95Limit", 3000)
        rows.append(
            f"| **{t.get('label', key)}** | {t.get('rps', 0)} | "
            f"{t.get('avg', 0)} | {t.get('med', 0)} | "
            f"{t.get('p95', 0)} | {t.get('p99', 0)} | "
            f"{t.get('errRate', 0)}% | {s(ok)} |"
        )

    tier_table = "\n".join(rows) if rows else "| — | — | — | — | — | — | — | — |"

    md = f"""# ⚡ OrbitX Load Testing Summary

## Overall Result: {emoji} {status}

> 🚀 **OrbitX Performance Test** — 4-Tier Virtual User Load Simulation

### 📊 Multi-Tier Performance Results

| Tier | Req/s | Avg (ms) | Median (ms) | P95 (ms) | P99 (ms) | Errors | Status |
|------|-------|----------|-------------|----------|----------|--------|--------|
{tier_table}

### 🎯 Threshold Validation

| Metric | Limit | Actual | Status |
|--------|-------|--------|--------|
| Average Response | < 1500 ms | {g['avg']} ms | {s(g['avg'] < 1500)} |
| P95 Response | < 3000 ms | {g['p95']} ms | {s(g['p95'] < 3000)} |
| P99 Response | < 5000 ms | {g['p99']} ms | {s(g['p99'] < 5000)} |
| Error % | < 5.0% | {g['errRate']}% | {s(g['errRate'] < 5.0)} |
| Throughput | > 10 req/s | {g['rps']} req/s | {s(g['rps'] > 10)} |
| Availability | > 95% | {round(100 - g['errRate'], 1)}% | {s(g['errRate'] < 5.0)} |

### 🌐 Global Telemetry

| Metric | Value |
|--------|-------|
| **Total Requests** | {g['reqs']:,} |
| **Requests/sec** | {g['rps']} |
| **Average Response** | {g['avg']} ms |
| **P95** | {g['p95']} ms |
| **P99** | {g['p99']} ms |
| **Max** | {g.get('max', 'N/A')} ms |
| **Error Rate** | {g['errRate']}% |
| **Overall Status** | **{status}** |

---
*Generated by OrbitX k6 Performance Engine*
"""
    return md


def build_perf_json(data: dict) -> dict:
    """Structured JSON consumed by aggregate_reports.py."""
    g = data.get("global", MOCK_DATA["global"])
    tiers = data.get("tiers", MOCK_DATA["tiers"])
    overall_ok = g["errRate"] < 5.0 and g["p95"] < 3000
    return {
        "status": "PASSED" if overall_ok else "FAILED",
        "global": g,
        "tiers": tiers,
        "score": max(0, min(100, round(
            100 - g["errRate"] * 5 - max(0, (g["p95"] - 200) / 60)
        ))),
    }


def main():
    os.makedirs("reports", exist_ok=True)
    summary_path = "reports/k6-summary.json"
    data = load_k6_summary(summary_path)

    md = build_markdown(data)
    with open("reports/performance-report.md", "w", encoding="utf-8") as f:
        f.write(md)
    print("[k6 Parser] ✅  reports/performance-report.md written")

    perf_json = build_perf_json(data)
    with open("reports/performance.json", "w", encoding="utf-8") as f:
        json.dump(perf_json, f, indent=2)
    print("[k6 Parser] ✅  reports/performance.json written")

    step_summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if step_summary:
        try:
            with open(step_summary, "a", encoding="utf-8") as f:
                f.write(md)
            print("[k6 Parser] ✅  Written to GITHUB_STEP_SUMMARY")
        except Exception as exc:
            print(f"[k6 Parser] ⚠️  GITHUB_STEP_SUMMARY write failed: {exc}", file=sys.stderr)


if __name__ == "__main__":
    main()
